### ISSUE TITLE
enable Cynara unit testing

### ISSUE THREAD

**Issue by pohly** [01org/meta-intel-iot-security#12]
The upstream Cynara project has unit tests in the repo. They depend on components not readily available in OE-core, so we can only enable them if those dependencies are satisfied somehow, i.e. enable the tests conditionally.

In addition, a separate repo of tests was mentioned at some point. Not sure whether that's really correct. Need to check with Cynara devs.

**Comment by johnwhiteman** [comment]
I have asked to Alexandru Cornea from Security QA team to request access. Like the other question ... is where will these test reside.  Also is there is common unit test framework that we want strive for (if possible since upstream can mean anything)?  More or less about unit tests that are applicable to OE-core.

**Comment by pohly** [comment]
Each component may use its own unit testing framework. This gets bundled in OE as "ptests", see http://www.yoctoproject.org/docs/1.6.1/dev-manual/dev-manual.html#testing-packages-with-ptest

The problem with Cynara is that it depends on gmock, which is only in meta-oe, but not oe-core. In the cynara recipe, we must add a PACKAGECONFIG for enabling tests, off by default, and then the user of the recipe is responsible for adding a suitable layer with gmock.

**Comment by johnwhiteman** [comment]
Alex Cornea is looking into this now.

**Comment by pohly** [comment]
Because we had issues with running Cynara (turned out to be something else), I looked into this myself today. See https://github.com/01org/meta-intel-iot-security/pull/17

**Comment by johnwhiteman** [comment]
Thank you.

**Comment by pohly** [comment]
Closing as "obsolete" because Ostro OS is not using Cynara at the moment. Can be reopened if someone wants to work on it.
