### ISSUE TITLE
extend the Smack security tests

### ISSUE THREAD

**Issue by pohly** [01org/meta-intel-iot-security#13]
At the moment, only file system labeling is tested. We also need tests for:
- correct rules
- enforcement of these rules by the kernel

**Comment by johnwhiteman** [comment]
I'm talking with Security Romania QA team about this now. One question is where will the new tests reside?

**Comment by pohly** [comment]
In the meta-security-smack layer. See https://github.com/01org/meta-intel-iot-security/commit/82a4801dac4d1938f6f11012c7fd30460744c2ac for an example.

**Comment by johnwhiteman** [comment]
Ok. Alex Cornea is looking into this now.

**Comment by pohly** [comment]
We have additional tests now.
